language: ruby
bundler_args: --path $HOME/.bundle
cache:
  directories:
    - $HOME/.bundle

before_script:
 - gem install html-proofer -v '~> 3.8'

script:
 - bundle exec jekyll build
 - htmlproofer ./_site --disable-external --empty-alt-ignore

before_deploy:
 - LAST_GIT_TAG="$(git describe --abbrev=0 --tags)"
 - tar -cvzf "$LAST_GIT_TAG.tar.gz" -C _site/ .

deploy:
- provider: pages
  skip-cleanup: true
  local-dir: _site
  github-token: $GITHUB_TOKEN
  on:
    branch: master
- provider: releases
  skip_cleanup: true
  file: "$LAST_GIT_TAG.tar.gz"
  api_key: $GITHUB_TOKEN
  on:
    branch: master
    tags: true

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

